ChangeLog
google/ads/google_ads/__init__.py
google/ads/google_ads/client.py
setup.py
tests/client_test.py

Addresses this issue: https://github.com/googleads/google-ads-python/issues/16
Implementation based [on this](https://github.com/grpc/grpc/blob/master/examples/python/interceptors/headers/header_manipulator_client_interceptor.py) example from grpc.

Fix bug related to augmenting client call details metatadata

---

ChangeLog
setup.py

PyYAML 4.2 is experimental, so install with `pip install PyYAML==4.2b4`

Updating PyYAML dependency due to security issue

---

ChangeLog
google/ads/google_ads/__init__.py
setup.py

Imports the `google.longrunning` module, which is used [here](https://github.com/googleads/google-ads-python/blob/master/google/ads/google_ads/v1/proto/services/mutate_job_service_pb2.py#L18) for LROs.

Install googleapis-common-protos to support LROs

---

ChangeLog
google/ads/google_ads/__init__.py
google/ads/google_ads/v1/proto/enums/bidding_source_pb2.py
setup.py

This was mistakenly left out of the v1 release. It resolves this issue: https://github.com/googleads/google-ads-python/issues/49

Update bidding_source_pb2 proto

---

examples/basic_operations/pause_ad.py
examples/basic_operations/remove_ad.py
examples/basic_operations/remove_keyword.py
examples/basic_operations/update_keyword.py
google/ads/google_ads/util.py
tests/util_test.py

Instead of requiring composite ID strings to be concatenated by the user, this simply adds a utility that does it for them.

Add utility to format composite resource names

---

google/ads/google_ads/client.py
tests/client_test.py

JSON Serialization of fields such as `video_quartile_25_rate` that contain a digit following an underscore will raise errors in Python.
This is expected behavior because it's not possible to serialize from snake_case to camelCase and back when a digit follows an underscore.
The fields in the API that contain this pattern are technically breaking this convention, but until a broader resolution is arrived at it's easier for now to simply not serialize messages to JSON for the purposes of logging because proto objects serialize to string very well on their own already.
This PR also introduces some general refactoring and cleanup.

Remove JSON serialization of Proto messages

---

README.rst
google-ads.yaml
google/ads/google_ads/client.py
google/ads/google_ads/config.py
google/ads/google_ads/oauth2.py
tests/client_test.py
tests/config_test.py
tests/oauth2_test.py

**NOTE**: This change includes breaking changes listed below. It should be released along a major version boundary:
* The `client._get_client_kwargs_from_env` method is removed.
* The `client._get_client_kwargs_from_yaml` method is removed.
* The `client._validate_login_customer_id` method is moved to `google.ads.google_ads.config.validate_login_customer_id`.

Add Service account support and refactor credentials and oauth logic.

---

ChangeLog
google/ads/google_ads/__init__.py
google/ads/google_ads/client.py
google/ads/google_ads/config.py
setup.py
tests/client_test.py
tests/config_test.py

Previously the `login_customer_id` config value was converted to a str in the client module [here](https://github.com/googleads/google-ads-python/blob/master/google/ads/google_ads/client.py#L59). Since validation of login customer id was moved to the new config module validation occurred before this step, and IDs that were of type `int` raised an error because they have no method `isdigit`.
This change adds a mechanism to the config module that parses config values, converting `login_customer_id` to a string before validation occurs.

Move conversion of login_customer_id to a str to config module

---

google/ads/google_ads/v2/services/customer_service_client.py

When this was initially generated for v2 `email_address` and `access_role` were erroneously marked as required. A fresh regeneration marks them as optional as is expected.'
Fixes: https://github.com/googleads/google-ads-python/issues/158

Regenerate customer_service for v2

---

examples/hotel_ads/add_hotel_ad.py

- Removed some unnecessary comments
- Example wasn't running due to `-h` for `--hotel_center_account_id` conflicting with the `-h` for `--help`, changed to `-a`
- Example wasn't running due to `str` being used for `hotel_center_account_id` had to change to `int`
- There was a change for Hotels that causes an error when setting AdGroupAd to `PAUSED` and should always be `ENABLED`.

Fixing add_hotel_ad.py

---

google/ads/google_ads/client.py

Python’s default arguments are evaluated once when the function is defined, not each time the function is called. This means that if you use a mutable default argument and mutate it, you will and have mutated that object for all future calls to the function as well.

removed using list[] directly as default args in GoogleAdsClient

---

google/ads/google_ads/v2/types.py

Retrieving class names using `getmembers` on pb2 modules returns _all_ classes, including some which are not protobuf message classes, (namely `google.longrunning.operations_pb2.OperationsStub`). Since we use types.py to consolidate protobuf message classes for easy access by the `client.get_type` method we want to use `get_messages` to limit the exposed classes to just protobuf message classes.

Use get_message helper when exporting dependent types for v2

---

google/ads/google_ads/interceptors/interceptor.py
tests/interceptors/interceptor_test.py

Loading `_pb2` modules is a known bottleneck and this change defers the cost until the module is needed for exception handling.

Defer loading of error_pb2 module until an exception is found in a response

---

google/ads/google_ads/interceptors/interceptor.py
tests/interceptors/interceptor_test.py

When implementing streaming interceptors for v3 we moved the logic to parse and instantiate `GoogleAdsExceptions` into the `Interceptor` parent class because the logging interceptor for unary-streaming requests needs access to this functionality. This is for two reasons:
1. Unary-streaming interceptors are not executed in a guaranteed order.
2. There's no mechanism to pass exceptions between interceptors, like there is in unary-unary requests.
While implementing the shared logic we cached the exception on the parent class in an attempt to reduce the number of times it needed to be created. However that caused exceptions to be cached across requests, as a single Interceptor class is instantiated for each _service_.
This PR removes that caching mechanism and adds a test ensuring sequential …

Fix Response Error Caching in Streaming Interceptors

---

google/ads/google_ads/v2/__init__.py
google/ads/google_ads/v3/__init__.py

`enums` and `types` don't fit the same pattern as the other classnames/files in the map, where a capitalized classname has a corresponding snakecase file name, i.e. `GoogleAdsService` and `google_ads_service` so this removes them from the map and exposes them via separate functionality. 
Resolves: https://github.com/googleads/google-ads-python/issues/260

Update versioned __init__ file to isolate enums and types

---

google/ads/google_ads/v2/services/enums.py
google/ads/google_ads/v3/services/enums.py

Use `exec` instead of `six.exec_`
Indent string-based inner-class definition and dedent on retrieval
Fix misnamed inner-classnames that contained trailing `'Enum'`
Fixes: https://github.com/googleads/google-ads-python/issues/199

Fix bugs in services/enums.py

---

ChangeLog
google/ads/google_ads/interceptors/logging_interceptor.py
tests/interceptors/logging_interceptor_test.py

The `GetCustomerRequest` object sends a resource name instead of a customer ID so this updates the logging interceptor slightly to parse the customer ID from it. 
Mirroring change made in Ruby here: https://github.com/googleads/google-ads-ruby/pull/29/files

Update retrieval of customer ID

---

google/ads/google_ads/v2/services/enums.py
google/ads/google_ads/v3/services/enums.py
tests/client_test.py

Add test enforcing `service_client.enums` interface.
Remove non-v2 Enums from `v2/services/enums.py`
Update validation in lazy-loaded enums to check for inner Enum: `Operator`.
Fixes: https://github.com/googleads/google-ads-python/issues/267

Fix issues with `services/enums.py`

---

examples/extensions/add_sitelinks.py

This line wasn't tested previously because it only executes if the current date is after Nov. 20.

Fix syntax error in add_sitelink.py example

---

examples/extensions/add_lead_form_extension.py

Adding a duplicate `PHONE_NUMBER` LeadFormField caused an error in our function test framework.

Fix bug in add_lead_form_extension example.

---

examples/hotel_ads/add_hotel_listing_group_tree.py

This example wasn't correctly creating entities to cover the "others" case, as is done [here](https://github.com/googleads/google-ads-php/blob/master/examples/HotelAds/AddHotelListingGroupTree.php#L260) in the PHP example.

Fix issues in add_hotel_listing_group_tree example

---

google/ads/googleads/v5/__init__.py
google/ads/googleads/v6/__init__.py
google/ads/googleads/v7/__init__.py
noxfile.py
setup.py

* Update unit tests to run in Python 3.6 and 3.7
* Add `dataclasses` dependency for Python 3.6 compatibility.
* Update __init__.py files where __getattr__ is used at the module level.

Fix bug breaking Python 3.6 compatibility.

---

examples/misc/set_custom_client_timeouts.py

Update custom client timeouts example with information about default behavior.

---

examples/campaign_management/get_campaigns_by_label.py

Came across this small little mis match in the `print` statement whilst fetching all campaigns by label

Fix typo in campaign management example

---

examples/authentication/generate_user_credentials.py

This PR corrects a typo that was introduced in PR #691. In that PR the definition of this method on line 99 had the underscore removed, but did not change how it was called on line 85. This PR allows the example to run again.

Corrects typo in generate_user_credentials example

---

examples/advanced_operations/add_responsive_search_ad_full.py

The `_LOCALE` and `_COUNTRY_CODE` parameters on the `gtc_request` object below are not present:
```python
geo_target_constant_service = client.get_service(
"GeoTargetConstantService"
)
gtc_request = client.get_type("SuggestGeoTargetConstantsRequest")
```
See https://github.com/googleads/google-ads-python/blob/b6a5dffccc25872fd38925926e59988186e3cc15/examples/targeting/get_geo_target_constants_by_names.py#L34-L60 for the updated usage of this object. 
This PR updates usage in the `add_responsive_search_add_full.py` script example.

update _LOCALE and _COUNTRY_CODE parameters to locale and country_code

---

examples/basic_operations/get_campaigns.py

Add an includecode section in get_campaigns.py so it can be used in the "Getting Started" guide.

Add an includecode section in get_campaigns.py

---

examples/shopping_ads/add_shopping_product_ad.py

To align with the [code example change](https://github.com/googleads/google-ads-java/pull/742) requested for the Java client library.
As seen in this [blog announcement](https://ads-developers.googleblog.com/2023/09/google-ads-shopping-campaign-enhanced.html), any Shopping campaigns using Enhanced cost-per-click (eCPC) will behave as if they are using Manual cost-per-click (CPC) bidding.
Because of the change, I'm updating the examples related to the announcement to reflect the new recommended practice.

Remove the usage of eCPC bidding because of its deprecation

---

noxfile.py
tests/client_test.py
tests/config_test.py
tests/interceptors/exception_interceptor_test.py
tests/interceptors/interceptor_test.py
tests/interceptors/logging_interceptor_test.py
tests/interceptors/metadata_interceptor_test.py
tests/oauth2_test.py

`mock` was merged into Python 3.3 as `unittest.mock`: https://docs.python.org/dev/whatsnew/3.3.html
This PR updates the tests to use it rather than the backport packgae.

Move from `mock` to `unittest.mock`

---

noxfile.py

[`--buffer`](https://docs.python.org/3.11/library/unittest.html#cmdoption-unittest-b) captures stdout and stderr, stopping it from polluting the test run output. This is the default behaviour in pytest.
Before:
```
..............................................................The 'path_to_private_key_file' configuration key and 'GOOGLE_ADS_PATH_TO_PRIVATE_KEY_FILE' environment variable are deprecated and support will be removed at some point in the future. Please use 'json_key_file_path' configuration key or 'GOOGLE_ADS_JSON_KEY_FILE_PATH' environment variable instead.
The 'delegated_account' configuration key and 'GOOGLE_ADS_DELEGATED_PATH' environment variable are deprecated and support will be removed at some point in the future. Please use 'impersonated_email' configuration key or …
```

Use unittest's `--buffer` option

---

examples/remarketing/upload_enhanced_conversions_for_web.py

Only first and last name in the physical address need to be normalized and hashed. See also [this Help Center article](https://support.google.com/google-ads/answer/13258081).

Remove normalization and hashing of postal code and country code

---

examples/remarketing/upload_enhanced_conversions_for_web.py

Should be using country_code and postal_code (see [ref](https://developers.google.com/google-ads/api/reference/rpc/v15/OfflineUserAddressInfo)). Sorry I missed this on my last PR.

Update address_info fields

---

examples/remarketing/upload_offline_conversion.py

Ref: b/310739611
Change-Id: Ide8079c878fb3f5a5d5d7220e0e00a35d987d4f3

Demonstrate passing consent in offline conversion upload

---

examples/advanced_operations/add_performance_max_campaign.py

**Context**: currently the `add_performance_max_campaign.py` example only contains code samples to add the audience signal as an asset group signal. We also support adding search themes as an asset group signal, which is documented [here](https://developers.google.com/google-ads/api/performance-max/asset-group-signals#search_themes). With that we want to modify our code example to include it.
**Changes**:
1. Added code to demonstrate adding a search theme asset group signal.
2. Updated the document links in comments.
3. Updated the positions of utility comments (`[START/END add_performance_max_campaign_*]`) to prepare for devsite updates.

Add example code for PMax campaigns to add search theme signal

---

examples/basic_operations/add_campaigns.py

Sets ManualCpc without setting the deprecated enhanced_cpc_enabled field (see [context](https://support.google.com/google-ads/answer/2464964)).

Fix add campaigns example

---

examples/remarketing/upload_enhanced_conversions_for_leads.py
examples/remarketing/upload_enhanced_conversions_for_web.py

If `email_address` has no `"@"` in it, the function raises `IndexError list index out of range` in:
```
is_gmail = re.match(r"^(gmail|googlemail)\.com$", email_parts[1])
```
because `email_parts` is a list with only one item.
This PR fix this bug by moving the above line inside the if-block `if len(email_parts) > 1` .
I've added `strip` to `email_address` to honor the [Enhanced Conversions doc](https://developers.google.com/google-ads/api/docs/conversions/enhance-conversions#python) which says:
> [...] In order to standardize the hash results, prior to hashing one of these values you must:
> - Remove leading/trailing whitespaces.
> - [...]

Fix bug in normalize_and_hash_email_address function

---

examples/billing/add_account_budget_proposal.py
examples/billing/add_billing_setup.py
examples/billing/get_invoices.py

This change adds type annotations and hints to the Python files in the examples/billing directory to improve code readability and maintainability.
Type hints were added to function arguments and return values for:
- add_account_budget_proposal.py
- add_billing_setup.py
- get_invoices.py

Add type hints to examples/billing

---

examples/targeting/add_campaign_targeting_criteria.py
examples/targeting/add_customer_negative_criteria.py
examples/targeting/add_demographic_targeting_criteria.py
examples/targeting/get_geo_target_constants_by_names.py

This change introduces type annotations to the Python scripts in the examples/targeting/ directory.
Type hints were added for:
- Function arguments and return values.
- Key local variables, particularly those interacting with the Google Ads API.
- GoogleAdsClient instances and argparse.Namespace objects.
The typing.Any type was used for complex Google Ads API objects where specific types were not readily apparent. This improves code readability and maintainability by making type expectations explicit.

Add type hints to examples/targeting
