googleads/google-ads-python

- examples/v0/recommendations/dismiss_recommendation.py
This example is similar to `apply_recommendations`
https://github.com/googleads/google-ads-python/blob/master/examples/v0/recommendations/apply_recommendation.py
> Add dismiss_recommendation example

- ChangeLog
- google/ads/google_ads/__init__.py
- setup.py
Merging this without approvals as it's just a version bump PR.
> Release version 1.3.0

- README.rst
> Add wiki link to README

- google/ads/google_ads/client.py
- google/ads/google_ads/config.py
- tests/client_test.py
- tests/config_test.py
Credentials can be instantiated in a dictionary and  be passed for initialization.
> Added Feature(Load_from_dict) in configuration file. 

- ChangeLog
- google/ads/google_ads/__init__.py
- google/ads/google_ads/v2/types.py
- setup.py
- Fix for types.py to include classes of dependent modules. See #196
> Release 4.1.1

- google/ads/google_ads/interceptors/exception_interceptor.py
> Fix exception interceptor protobuf decode issue

- examples/reporting/get_hotel_ads_performance.py
Fix get hotel ads performance report example.
> Fix get hotel ads performance report example

- examples/misc/get_all_image_assets.py
- examples/misc/upload_image.py
- examples/misc/upload_image_assets.py
Based on https://github.com/googleads/google-ads-dotnet/tree/master/examples/Misc
> Add uploadimageasset

- examples/extensions/add_prices.py
PHP equivalent: https://github.com/googleads/google-ads-php/pull/265
> Added add_prices.py feed extension example

- examples/misc/upload_media_bundle.py
Based on https://github.com/googleads/google-ads-php/pull/255
> upload media bundle example

- examples/remarketing/upload_offline_conversion.py
Code is not yet tested with real data
> added upload_offline_conversion. 

- examples/remarketing/upload_conversion_adjustment.py
- examples/remarketing/upload_offline_conversion.py
Based on https://github.com/googleads/google-ads-php/pull/263
> Add uploadconversionadjustment

- examples/advanced_operations/add_app_campaign.py
Google Ads API golden version of https://github.com/googleads/googleads-python-lib/blob/master/examples/adwords/v201809/advanced_operations/add_universal_app_campaign.py
> add_app_campaign golden example

- examples/reporting/get_keyword_stats.py
Replaces https://github.com/googleads/google-ads-python/pull/185
> updated get_keyword_stats for enum and styling

- examples/basic_operations/add_responsive_search_ad.py
- examples/basic_operations/get_responsive_search_ads.py
Google Ads API golden version of https://github.com/googleads/googleads-python-lib/blob/master/examples/adwords/v201809/basic_operations/get_responsive_search_ads.py
Also added add_responsive_search_ad.py because it was missing from Python
> get_responsive_search_ads golden (also includes missing add_responsive_search_ad example)

- examples/campaign_management/validate_text_ad.py
Per change in https://github.com/googleads/google-ads-java/pull/239/commits/0e2b344cc87c684857861026156af7c4cbacfcb8
> added comment to validate_text_ad example

- examples/advanced_operations/add_app_campaign.py
also split ad group and app ad creation and minor formatting.
Based on review comments in https://github.com/googleads/google-ads-php/pull/275
> add_app_campaign: fixed multiple campaign criteria

- examples/basic_operations/get_responsive_search_ads.py
1) Added useful comment re: optional parameter
2) Took out check for responsive_search_ad_info and cleaned up.
> updates to get_responsive_search_ads example

- examples/advanced_operations/add_dynamic_search_ads.py
We already had an existing example for `add_dynamic_search_ads` that was misnamed, here I rename it to be consistent with other libraries as well as update some comments for consistency and update some syntax.
> Update add_dynamic_search_ads example

- examples/basic_operations/get_expanded_text_ads.py
- examples/billing/get_billing_setup.py
As part of doc update to streaming, moving over two old examples to streaming
> converted two old examples to use search_stream

- examples/campaign_management/add_campaign_labels.py
Adding a missing code example to be consistent with other libraries.  Will complement the transfer and update of Labels guide from AdWords API.
> Added add_campaign_labels example

- examples/error_handling/handle_rate_exceeded_error.py
Based on [this example](https://github.com/googleads/google-ads-php/blob/master/examples/ErrorHandling/HandleRateExceededError.php) from PHP.
> Add `handle_rate_exceeded` error.

- examples/account_management/reject_merchant_center_link.py
- examples/advanced_operations/add_display_upload_ad.py
- examples/extensions/add_affiliate_location_extensions.py
- examples/extensions/update_sitelink.py
- examples/extensions/update_sitelink_campaign_extension_setting.py
- examples/hotel_ads/add_hotel_listing_group_tree.py
- examples/shopping_ads/add_shopping_smart_ad.py
Adding update_sitelink_campaign_extension_setting.py example. I also ran `black` and included the formatting changes from that (but can move those to a separate PR if preferred).
> Update sitelink campaign extension setting

- examples/extensions/add_lead_form_extension.py
- examples/shopping_ads/add_listing_scope.py
- examples/shopping_ads/add_shopping_product_listing_group_tree.py
These are bugs that were discovered in existing examples as @wfansh has added additional tests to our Example test framework.
> Bugfixes for examples

- examples/feeds/create_feed_item_set.py
Main thing I'm looking for feedback on is the location extension / affiliate extension code. Without a GMB account, I wasn't able to test this (but I did verify that the protos are properly set)
> create_feed_item_set example

- examples/feeds/link_feed_item_set.py
Ran this through FT and got success message
> Add link_feed_item_set example

- examples/remarketing/add_customer_match_user_list.py
Adds a demonstration of how to get the lists upload status without polling.
Fixes: #378
> Update add_customer_match_user_list example

- examples/campaign_management/validate_text_ad.py
All detail in this [blog post](https://ads-developers.googleblog.com/2021/01/ad-policy-error-management-is-evolving.html).
> Fix comment in ValidateTextAd code example

- examples/account_management/get_account_hierarchy.py
- This fixes #364
- Fixes the recursion calls of the printing hierarchy function
> Normalize datatypes of customer_ids_to_child_accounts dict to integers

- .github/ISSUE_TEMPLATE/config.yml
Per the instructions [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser)
> Disallow blank issues

- examples/authentication/authenticate_in_web_application.py
This is primarily based on the [Ruby example](https://github.com/googleads/google-ads-ruby/blob/master/examples/authentication/authenticate_in_web_application.rb), where a single socket is used to receive the Auth request and parse the auth token from query params.
> Update authenticate via web flow example

- examples/basic_operations/update_keyword.py
- examples/recommendations/apply_recommendation.py
Grepped for an example based on the description and found multiple unrelated examples with that description 😬
> update incorrect descriptions

- examples/extensions/add_affiliate_location_extensions.py
plus some `black` reformatting
> Fix typos in add_affiliate_location_extensions

- google-ads.yaml
> Update sample YAML file to clarify steps for service accounts.

- examples/feeds/update_flights_feed_item_string_attribute_value.py
CopyFrom was doing the same thing as the preceding copy_from helper
> Remove duplicate code

- examples/recommendations/apply_recommendation.py
Fixes https://github.com/googleads/google-ads-python/issues/549
> Demonstrate how to use apply_parameters

- setup.py
For Google Ads API v10 release
> Update google-ads version to 15.0.0

- examples/recommendations/dismiss_recommendation.py
> Fix dismiss_recommendation_example.

- examples/account_management/link_manager_to_client.py
* Added missing import sys
* Corrected variable referring to exception
* Pass customer_id to mutate_customer_manager_link call.
> Update link_manager_to_client example.

- google/ads/googleads/client.py
- google/ads/googleads/oauth2.py
Link to Issue:
https://github.com/googleads/google-ads-python/issues/671
I did what @BenRKarl asked me to.
> fix problems proxy: add https protocol

- examples/shopping_ads/add_performance_max_retail_campaign.py
Minor refactoring, and sorts the list of assets and asset group assets so that assets come first. This avoids known errors in the API. Also uses a new third image for Logo, because duplicate images are not allowed. Also makes a number of style changes.
> Fix bug in performance max retail campaign.

- setup.py
> Correct version in setup.py.

- examples/remarketing/upload_offline_conversion.py
Addresses bug brought up in https://github.com/googleads/google-ads-python/issues/710
> Fix bug in upload_offline_conversion example.

- google/ads/googleads/client.py
Resolves https://github.com/googleads/google-ads-python/issues/740
> Update error message raised when getting a service from an invalid API version.

- examples/remarketing/add_customer_match_user_list.py
Move the closing tag up for consistency with other examples.
> Relocate closing tag in add_customer_match_user_list.py

- examples/advanced_operations/add_dynamic_page_feed_asset.py
- examples/campaign_management/add_complete_campaigns_using_batch_job.py
- examples/error_handling/handle_keyword_policy_violations.py
- examples/google-ads-account-analyzer-demo/analyzer.py
- examples/hotel_ads/add_performance_max_for_travel_goals_campaign.py
- examples/recommendations/detect_and_apply_recommendations.py
- examples/shopping_ads/add_performance_max_product_listing_group_tree.py
- google/ads/googleads/client.py
- google/ads/googleads/v12/common/types/keyword_plan_common.py
- google/ads/googleads/v12/errors/types/customer_client_link_error.py
- google/ads/googleads/v12/errors/types/errors.py
- google/ads/googleads/v12/resources/types/feed_item.py
- google/ads/googleads/v12/resources/types/lead_form_submission_data.py
- google/ads/googleads/v12/services/services/keyword_plan_ad_group_keyword_service/transports/grpc.py
- google/ads/googleads/v12/services/types/google_ads_service.py
- google/ads/googleads/v13/common/types/keyword_plan_common.py
- google/ads/googleads/v13/errors/types/customer_client_link_error.py
- google/ads/googleads/v13/errors/types/errors.py
- google/ads/googleads/v13/resources/types/feed_item.py
- google/ads/googleads/v13/resources/types/lead_form_submission_data.py
- google/ads/googleads/v13/services/services/keyword_plan_ad_group_keyword_service/transports/grpc.py
- google/ads/googleads/v13/services/types/google_ads_service.py
- tests/client_test.py
- tests/interceptors/logging_interceptor_test.py
- tests/util_test.py
Fixed some typos in comments, docstrings and a method name.
> Fix Typos & Method Names

- examples/remarketing/add_customer_match_user_list.py
Equivalent update in Perl: https://github.com/googleads/google-ads-perl/pull/106/files
> Update tags in Customer Match example

- examples/advanced_operations/add_responsive_search_ad_full.py
- examples/assets/add_sitelinks.py
- examples/recommendations/detect_and_apply_recommendations.py
1. Address comments in add_responsive_search_ad_full
2. Remove unused param in add_sitelinks
3. Refactor detect_and_apply_recommendations to use batch mutates
> Fix issues in three examples:

- examples/recommendations/detect_and_apply_recommendations.py
Adds two new devsite tags: `build_apply_recommendation_operation` and `detect_keyword_recommendations` 
See https://github.com/googleads/google-ads-perl/pull/124 and cl/620247165
> Add new recommendation devsite tags

- examples/recommendations/generate_budget_recommendations.py
- examples/recommendations/get_recommendation_impact_metrics.py
I've added 2 important examples of the new feature Budget Recommendations, which was launched in Google Ads API v18.
I've iterated based on Laura's feedback (@laurachevalier4 ). I had to create a new PR and I closed the previous one (#904 ). 
If you have feedback, please let me know and I can work on the changes, but don't change the PR as it complicates things on my end. Thanks!
> Added 2 Important Examples for New Feature Budget Recommendations

- examples/audience_insights/generate_audience_insights.py
Adding code snippets for Audience Insights APIs for Google Ads.
> Add code samples for audience insights APIs

- examples/authentication/generate_user_credentials.py
This change adds type hints to the functions in
`examples/authentication/generate_user_credentials.py` to improve code readability and maintainability.
> Add type hints to examples/authentication

- examples/recommendations/detect_and_apply_recommendations.py
- examples/recommendations/dismiss_recommendation.py
- examples/recommendations/generate_budget_recommendations.py
- examples/recommendations/get_recommendation_impact_metrics.py
This change adds type hints and annotations to the Python files in the examples/recommendations directory. This improves code readability and helps with static analysis.
The following files were modified:
- detect_and_apply_recommendations.py
- dismiss_recommendation.py
- generate_budget_recommendations.py
- get_recommendation_impact_metrics.py
> Added type hints to examples/recommendations

- examples/reporting/parallel_report_download.py
This change adds type annotations and hints to the examples/reporting/parallel_report_download.py script.
Type hints were added for function arguments, return values, and key variables to improve code readability and maintainability. Necessary types were imported from the `typing` module.
> Add type hints to examples/reporting

- examples/utils/example_helpers.py
Specifically, I added return type annotations to the following functions:
- `get_printable_datetime`
- `get_image_bytes_from_url`
> Added type hints to `example_helpers.py`.
